import type { Document, Finding, Grade } from "./types.ts";

/**
 * Explicit, tunable scoring weights. Score starts at WEIGHTS.base, gains
 * positive signal points, loses points for negative signals and findings,
 * then is clamped to 0..100.
 */
export const WEIGHTS = {
  base: 100,

  // Finding penalties (per finding).
  errorPenalty: -12,
  warnPenalty: -6,
  infoPenalty: -1,

  // Positive signals (added once when present).
  hasBuildAndTest: 3,
  commandsEarly: 2,
  hasBoundaries: 2,
  hasSecurityNote: 1,
  neverCommitSecrets: 1,
  pairedDoDont: 1,
  hasShortExamples: 2,
  hasVersions: 1,
  linksWithinBudget: 1,
  idealLength: 3,

  // Negative signals (subtracted once when present).
  overSoftLength: -4,
  overHeavyLength: -10,
  bigArchitectureProse: -6,
  tooManyLinks: -4,
  tooManyExamples: -3,
  looksAutoGenerated: -8,
  readmeDuplication: -4,
} as const;

/** Score band lower bounds for each letter grade. */
export const GRADE_BANDS: { min: number; grade: Grade }[] = [
  { min: 90, grade: "A" },
  { min: 80, grade: "B" },
  { min: 70, grade: "C" },
  { min: 60, grade: "D" },
  { min: 0, grade: "F" },
];

export function gradeFor(score: number): Grade {
  for (const band of GRADE_BANDS) {
    if (score >= band.min) return band.grade;
  }
  return "F";
}

function clamp(n: number): number {
  return Math.max(0, Math.min(100, Math.round(n)));
}

function hasCommand(doc: Document, pattern: RegExp): boolean {
  return doc.commands.some((c) => pattern.test(c.text));
}

function countLinks(doc: Document): number {
  const m = doc.raw.match(/\]\(([^)]+)\)/g);
  return m ? m.length : 0;
}

function countLines(raw: string): number {
  const trimmed = raw.replace(/\n+$/, "");
  return trimmed.length === 0 ? 0 : trimmed.split("\n").length;
}

/** Compute the 0-100 score and grade from the document and its findings. */
export function scoreDocument(
  doc: Document,
  findings: Finding[],
): { score: number; grade: Grade } {
  let score = WEIGHTS.base;

  // Finding penalties.
  for (const f of findings) {
    if (f.severity === "error") score += WEIGHTS.errorPenalty;
    else if (f.severity === "warn") score += WEIGHTS.warnPenalty;
    else score += WEIGHTS.infoPenalty;
  }

  const lower = doc.raw.toLowerCase();
  const lineCount = countLines(doc.raw);

  // Positive signals.
  const hasBuild =
    hasCommand(doc, /\b(build|compile|run build)\b/) || /\b(build)\b/.test(lower);
  const hasTest = hasCommand(doc, /\b(test|pytest|jest|vitest)\b/);
  if (hasBuild && hasTest) score += WEIGHTS.hasBuildAndTest;

  const firstCommandLine = doc.commands[0]?.line ?? Number.POSITIVE_INFINITY;
  if (firstCommandLine <= Math.max(20, lineCount * 0.4)) {
    score += WEIGHTS.commandsEarly;
  }

  const headingsLower = doc.headings.map((h) => h.text.toLowerCase());
  if (headingsLower.some((h) => /boundaries|never|always|ask first/.test(h))) {
    score += WEIGHTS.hasBoundaries;
  }
  if (/security|secret|credential/.test(lower)) {
    score += WEIGHTS.hasSecurityNote;
  }
  if (/never commit secrets|don'?t commit secrets/.test(lower)) {
    score += WEIGHTS.neverCommitSecrets;
  }
  if (/\bnever\b/.test(lower) && /\b(always|do |use |run )\b/.test(lower)) {
    score += WEIGHTS.pairedDoDont;
  }

  const exampleBlocks = doc.codeBlocks.filter((b) => {
    const n = b.value.split("\n").filter((l) => l.trim().length > 0).length;
    return n >= 3 && n <= 10;
  }).length;
  if (exampleBlocks >= 1 && exampleBlocks <= 3) {
    score += WEIGHTS.hasShortExamples;
  } else if (doc.codeBlocks.length > 5) {
    score += WEIGHTS.tooManyExamples;
  }

  if (/\b[v^~]?\d+(\.\d+){1,2}\b/.test(doc.raw)) {
    score += WEIGHTS.hasVersions;
  }

  const links = countLinks(doc);
  if (links > 0 && links <= 15) score += WEIGHTS.linksWithinBudget;
  else if (links > 15) score += WEIGHTS.tooManyLinks;

  if (lineCount >= 50 && lineCount <= 150) {
    score += WEIGHTS.idealLength;
  } else if (lineCount > 300) {
    score += WEIGHTS.overHeavyLength;
  } else if (lineCount > 150) {
    score += WEIGHTS.overSoftLength;
  }

  // Negative signals.
  if (
    /## (architecture|file tour|directory structure)/i.test(doc.raw) &&
    lineCount > 150
  ) {
    score += WEIGHTS.bigArchitectureProse;
  }
  if (/generated by|do not edit|auto-?generated|\/init\b/i.test(lower)) {
    score += WEIGHTS.looksAutoGenerated;
  }
  if (
    /this (project|repo) is a |## installation\n/i.test(lower) &&
    /see readme|as in the readme/i.test(lower)
  ) {
    score += WEIGHTS.readmeDuplication;
  }

  const finalScore = clamp(score);
  return { score: finalScore, grade: gradeFor(finalScore) };
}
